const COPY = {
  ro: {
    account: "Contul meu",
    signIn: "Autentificare",
    signInTitle: "Bine ai revenit",
    signInLead: "Autentifică-te pentru a vedea comenzile și adresele salvate.",
    register: "Creează cont",
    registerTitle: "Creează un cont",
    registerLead: "Comenzile, adresele și datele de contact vor fi la îndemână.",
    logout: "Ieșire",
    loggingOut: "Se închide sesiunea…",
    email: "Email",
    password: "Parolă",
    newPassword: "Parolă nouă",
    confirmPassword: "Confirmă parola",
    fullName: "Nume și prenume",
    phone: "Telefon",
    forgotPassword: "Ai uitat parola?",
    forgotTitle: "Resetarea parolei",
    forgotLead: "Introdu emailul contului. Dacă există, îți vom trimite un link valabil o oră.",
    sendReset: "Trimite instrucțiunile",
    forgotSent: "Dacă există un cont activ cu acest email, instrucțiunile au fost trimise.",
    resetTitle: "Alege o parolă nouă",
    resetLead: "Parola trebuie să conțină între 10 și 128 de caractere.",
    resetPassword: "Schimbă parola",
    resetDone: "Parola a fost schimbată. Te poți autentifica cu noua parolă.",
    invalidResetLink: "Linkul de resetare este incomplet sau nu este valid.",
    noAccount: "Nu ai cont?",
    haveAccount: "Ai deja cont?",
    required: "Completează acest câmp.",
    invalidEmail: "Introdu o adresă de email validă.",
    passwordLength: "Parola trebuie să conțină cel puțin 10 caractere.",
    passwordsMismatch: "Parolele nu coincid.",
    verifyHuman: "Confirmă verificarea anti-abuz.",
    turnstileMissing: "Verificarea anti-abuz nu este configurată. Setează VITE_TURNSTILE_SITE_KEY înainte de lansare.",
    turnstileError: "Verificarea nu a putut fi încărcată. Reîncarcă pagina și încearcă din nou.",
    loading: "Se încarcă…",
    saving: "Se salvează…",
    retry: "Încearcă din nou",
    save: "Salvează",
    cancel: "Anulează",
    edit: "Editează",
    delete: "Șterge",
    close: "Închide",
    back: "Înapoi",
    sessionExpired: "Sesiunea a expirat. Autentifică-te din nou.",
    profile: "Date personale",
    profileLead: "Aceste date vor completa automat comenzile viitoare.",
    profileSaved: "Datele personale au fost actualizate.",
    addresses: "Adrese",
    addressesLead: "Adresa implicită completează automat livrarea, fără a înlocui ce ai tastat deja.",
    addAddress: "Adaugă adresă",
    editAddress: "Editează adresa",
    noAddresses: "Nu ai încă nicio adresă salvată.",
    recipientName: "Destinatar",
    city: "Oraș / localitate",
    address: "Adresa de livrare",
    addressComment: "Detalii pentru curier (opțional)",
    defaultAddress: "Adresă implicită",
    makeDefault: "Setează implicită",
    addressSaved: "Adresa a fost salvată.",
    addressDeleted: "Adresa a fost ștearsă.",
    confirmDeleteAddress: "Sigur vrei să ștergi această adresă?",
    orders: "Comenzile mele",
    ordersLead: "Vezi starea, conținutul și totalul fiecărei comenzi.",
    allOrders: "Toate stările",
    filterStatus: "Filtrează după stare",
    loadMore: "Încarcă mai multe",
    noOrders: "Nu ai plasat încă nicio comandă din acest cont.",
    order: "Comanda",
    orderDate: "Data",
    orderItems: "Produse",
    catalogDiscount: "Reducere catalog",
    promoDiscount: "Cod promo {code}",
    orderTotal: "Total",
    orderStatus: "Stare",
    details: "Detalii",
    delivery: "Livrare",
    payment: "Plată",
    recipient: "Destinatar",
    statusHistory: "Istoricul stării",
    repeatOrder: "Adaugă din nou în coș",
    repeatingOrder: "Se verifică disponibilitatea…",
    repeatAdded: "Produsele disponibile au fost adăugate în coș.",
    repeatPartial: "Produsele disponibile au fost adăugate; unele articole sau cantități nu mai sunt disponibile.",
    repeatUnavailable: "Niciun produs din această comandă nu mai este disponibil.",
    catalogUnavailable: "Catalogul actual nu poate fi verificat acum. Coșul nu a fost modificat.",
    goCheckout: "Mergi la finalizare",
    itemUnavailableCount: "Indisponibile sau ajustate: {count}",
    returnedQuantity: "Returnate: {count}",
    requestReference: "Cod cerere: {id}",
    accountUnavailable: "Contul nu este disponibil momentan. Încearcă din nou.",
    status_pending: "În așteptare",
    status_confirmed: "Confirmată",
    status_processing: "În procesare",
    status_ready: "Pregătită",
    status_shipped: "Expediată",
    status_completed: "Finalizată",
    status_cancelled: "Anulată",
    status_returned: "Returnată",
    status_expired: "Expirată",
    itemsCount: "{count} produse",
    fromStatus: "de la {from}",
  },
  ru: {
    account: "Мой аккаунт",
    signIn: "Войти",
    signInTitle: "С возвращением",
    signInLead: "Войдите, чтобы видеть заказы и сохранённые адреса.",
    register: "Создать аккаунт",
    registerTitle: "Создайте аккаунт",
    registerLead: "Заказы, адреса и контактные данные всегда будут под рукой.",
    logout: "Выйти",
    loggingOut: "Завершаем сеанс…",
    email: "Email",
    password: "Пароль",
    newPassword: "Новый пароль",
    confirmPassword: "Подтвердите пароль",
    fullName: "Имя и фамилия",
    phone: "Телефон",
    forgotPassword: "Забыли пароль?",
    forgotTitle: "Сброс пароля",
    forgotLead: "Введите email аккаунта. Если он существует, мы отправим ссылку, действующую один час.",
    sendReset: "Отправить инструкции",
    forgotSent: "Если активный аккаунт с таким email существует, инструкции отправлены.",
    resetTitle: "Задайте новый пароль",
    resetLead: "Пароль должен содержать от 10 до 128 символов.",
    resetPassword: "Изменить пароль",
    resetDone: "Пароль изменён. Теперь можно войти с новым паролем.",
    invalidResetLink: "Ссылка для сброса неполная или недействительна.",
    noAccount: "Нет аккаунта?",
    haveAccount: "Уже есть аккаунт?",
    required: "Заполните это поле.",
    invalidEmail: "Введите корректный адрес email.",
    passwordLength: "Пароль должен содержать не менее 10 символов.",
    passwordsMismatch: "Пароли не совпадают.",
    verifyHuman: "Пройдите проверку от злоупотреблений.",
    turnstileMissing: "Проверка от злоупотреблений не настроена. Укажите VITE_TURNSTILE_SITE_KEY перед запуском.",
    turnstileError: "Не удалось загрузить проверку. Перезагрузите страницу и попробуйте ещё раз.",
    loading: "Загрузка…",
    saving: "Сохраняем…",
    retry: "Попробовать снова",
    save: "Сохранить",
    cancel: "Отмена",
    edit: "Изменить",
    delete: "Удалить",
    close: "Закрыть",
    back: "Назад",
    sessionExpired: "Сеанс истёк. Войдите снова.",
    profile: "Личные данные",
    profileLead: "Эти данные будут автоматически подставлены в будущие заказы.",
    profileSaved: "Личные данные обновлены.",
    addresses: "Адреса",
    addressesLead: "Адрес по умолчанию заполняет доставку, не заменяя уже введённые вами данные.",
    addAddress: "Добавить адрес",
    editAddress: "Изменить адрес",
    noAddresses: "У вас пока нет сохранённых адресов.",
    recipientName: "Получатель",
    city: "Город / населённый пункт",
    address: "Адрес доставки",
    addressComment: "Детали для курьера (необязательно)",
    defaultAddress: "Адрес по умолчанию",
    makeDefault: "Сделать основным",
    addressSaved: "Адрес сохранён.",
    addressDeleted: "Адрес удалён.",
    confirmDeleteAddress: "Удалить этот адрес?",
    orders: "Мои заказы",
    ordersLead: "Смотрите статус, состав и сумму каждого заказа.",
    allOrders: "Все статусы",
    filterStatus: "Фильтр по статусу",
    loadMore: "Загрузить ещё",
    noOrders: "Вы ещё не оформляли заказов из этого аккаунта.",
    order: "Заказ",
    orderDate: "Дата",
    orderItems: "Товары",
    catalogDiscount: "Скидка каталога",
    promoDiscount: "Промокод {code}",
    orderTotal: "Итого",
    orderStatus: "Статус",
    details: "Подробнее",
    delivery: "Доставка",
    payment: "Оплата",
    recipient: "Получатель",
    statusHistory: "История статуса",
    repeatOrder: "Снова добавить в корзину",
    repeatingOrder: "Проверяем наличие…",
    repeatAdded: "Доступные товары добавлены в корзину.",
    repeatPartial: "Доступные товары добавлены; некоторых позиций или количеств больше нет в наличии.",
    repeatUnavailable: "Ни одного товара из этого заказа больше нет в наличии.",
    catalogUnavailable: "Сейчас не удалось проверить актуальный каталог. Корзина не изменена.",
    goCheckout: "Перейти к оформлению",
    itemUnavailableCount: "Недоступно или скорректировано: {count}",
    returnedQuantity: "Возвращено: {count}",
    requestReference: "Код запроса: {id}",
    accountUnavailable: "Аккаунт временно недоступен. Попробуйте ещё раз.",
    status_pending: "Ожидает обработки",
    status_confirmed: "Подтверждён",
    status_processing: "В обработке",
    status_ready: "Готов к выдаче",
    status_shipped: "Отправлен",
    status_completed: "Завершён",
    status_cancelled: "Отменён",
    status_returned: "Возвращён",
    status_expired: "Истёк",
    itemsCount: "Товаров: {count}",
    fromStatus: "из статуса {from}",
  },
};

export function accountText(language, key, values = {}) {
  const dictionary = COPY[language] || COPY.ro;
  let value = dictionary[key] ?? COPY.ro[key] ?? key;
  for (const [name, replacement] of Object.entries(values)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}

const ERROR_KEYS = {
  INVALID_CREDENTIALS: { ro: "Emailul sau parola nu sunt corecte.", ru: "Неверный email или пароль." },
  ACCOUNT_ALREADY_EXISTS: { ro: "Există deja un cont cu acest email.", ru: "Аккаунт с таким email уже существует." },
  INVALID_EMAIL: { ro: "Introdu un email valid.", ru: "Введите корректный email." },
  INVALID_PASSWORD: { ro: "Parola trebuie să conțină între 10 și 128 de caractere.", ru: "Пароль должен содержать от 10 до 128 символов." },
  INVALID_NAME: { ro: "Introdu un nume valid.", ru: "Введите корректное имя." },
  INVALID_RECIPIENT_NAME: { ro: "Introdu numele destinatarului.", ru: "Введите имя получателя." },
  INVALID_PHONE: { ro: "Introdu un număr de telefon valid.", ru: "Введите корректный номер телефона." },
  INVALID_CITY: { ro: "Introdu orașul sau localitatea.", ru: "Введите город или населённый пункт." },
  INVALID_ADDRESS: { ro: "Introdu o adresă de livrare validă.", ru: "Введите корректный адрес доставки." },
  INVALID_COMMENT: { ro: "Comentariul este prea lung.", ru: "Комментарий слишком длинный." },
  INVALID_RESET_TOKEN: { ro: "Linkul de resetare este invalid sau a expirat.", ru: "Ссылка для сброса недействительна или истекла." },
  HUMAN_VERIFICATION_REQUIRED: { ro: "Confirmă verificarea anti-abuz.", ru: "Пройдите проверку от злоупотреблений." },
  HUMAN_VERIFICATION_FAILED: { ro: "Verificarea a expirat. Încearcă din nou.", ru: "Проверка истекла. Попробуйте снова." },
  RATE_LIMITED: { ro: "Prea multe încercări. Așteaptă puțin și încearcă din nou.", ru: "Слишком много попыток. Подождите и попробуйте снова." },
  ADDRESS_LIMIT_REACHED: { ro: "Ai atins limita de 20 de adrese.", ru: "Достигнут лимит в 20 адресов." },
  ADDRESS_NOT_FOUND: { ro: "Adresa nu a fost găsită sau a fost deja ștearsă.", ru: "Адрес не найден или уже удалён." },
  ORDER_NOT_FOUND: { ro: "Comanda nu a fost găsită.", ru: "Заказ не найден." },
  ACCOUNT_API_UNAVAILABLE: { ro: "Serviciul de cont nu este disponibil momentan.", ru: "Сервис аккаунта временно недоступен." },
  EMAIL_NOT_CONFIGURED: { ro: "Trimiterea emailurilor nu este configurată încă.", ru: "Отправка писем пока не настроена." },
};

export function accountErrorText(language, error) {
  return ERROR_KEYS[error?.code]?.[language] || ERROR_KEYS[error?.code]?.ro || accountText(language, "accountUnavailable");
}

export function orderStatusText(language, status) {
  return accountText(language, `status_${status}`);
}
